### ISSUE TITLE
Add data of publication

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#1104]
**Is your enhancement request related to a problem? Please describe.**
The project page does not list the publication date e.g. on https://nmrxiv.org/dashboard/projects/229 , while the data of the last update is displayed. 

**Describe the solution you'd like**
Publication date should be displayed. 

Best,
Tillmann

**Comment by NishaSharma14** [comment]
Hi @tilfischer,
This is fixed and deployed to prod. Please check once and let us know your feedback.

**Comment by tilfischer** [comment]
Dear Nisha,

Thank you for adding this! As you might expect, I still see some room for improvements. 

On https://doi.org/10.57992/nmrxiv.p62 it tells ``Published on: March 5, 2024 | Created on: November 30, 2022`` below the citation and additionally ``NOURA RAYYA UPDATED ON MARCH 5, 2024`` more to the top of the page. It is unclear why this information is spear at two places. Moreover, the "created on" does not seem to be required as this information does not seem to have any use case to me. Hence, I would suggest to replace "created on" with "updated on" and remove the "updated on" on the top of the page.

Best,
Tillmann
